# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - "airbnb-base"

parserOptions:
  ecmaVersion: latest

rules:
  no-console: "off"
  import/extensions: "off"
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]